### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by skeezerbean** [TylerDelmus/AOItemSwapTool#1]
I'm able to inject the DLL (old client) and get the pop up message it was successful, but performing the actions listed in the readme seems to have no response. I pick up bag #2, the bag closes like I'd expect when picked up, and right click on the bag #1 in inventory. There is no response, no bag-inside-bag action. Right clicking inside an empty spot in bag #1 (while picking up bag #2) does nothing, just in case that was something supposed to help. I tried with multiple types of bags, namely small/med/large.
I'm assuming this has been patched.

**Comment by angola1** [comment]
Yes, this was patched a while back.

**Comment by Tinked** [comment]
yea doesnt work sadly, there is a newer version which works and i'd love to get a copy of the dll

**Comment by MotoJunkie** [comment]
> yea doesnt work sadly, there is a newer version which works and i'd love to get a copy of the dll, i have a copy of the stacker which is working as of today i'd upload if wanted.

I am interested in it. I might have something you could use as well.

**Comment by skeezerbean** [comment]
This won't ever be fixed here, so closing
